# Generated by Django 3.0.7 on 2021-04-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uth_groups_app', '0002_auto_20210402_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
