# Generated by Django 3.0.7 on 2021-04-07 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uth_groups_app', '0005_auto_20210407_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploader',
            old_name='private',
            new_name='active',
        ),
    ]
