# Generated by Django 3.0.7 on 2021-04-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uth_groups_app', '0007_auto_20210407_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploader',
            name='available_space',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='uploader',
            name='total_space',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='uploader',
            name='used_space',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
