# Generated by Django 3.0.7 on 2021-04-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uth_groups_app', '0010_auto_20210408_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploader',
            name='available_space_str',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='uploader',
            name='total_space_str',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='uploader',
            name='used_space_str',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
