# Generated by Django 3.0.7 on 2021-04-11 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uth_groups_app', '0013_group_root_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_root_folders_ids',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uth_groups_app.Group'),
        ),
    ]
