# Generated by Django 3.2 on 2021-04-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uth_groups_app', '0014_auto_20210411_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='datetime',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
