# Generated by Django 3.2 on 2021-04-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uth_groups_app', '0016_alter_group_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='participants',
            field=models.ManyToManyField(related_name='Participants', to='uth_groups_app.Student'),
        ),
        migrations.AlterField(
            model_name='group',
            name='participants',
            field=models.ManyToManyField(to='uth_groups_app.Student'),
        ),
    ]
