# Generated by Django 3.2 on 2021-05-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uth_groups_app', '0017_auto_20210424_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='code',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
