# Generated by Django 3.2 on 2021-05-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uth_groups_app', '0019_alter_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
