# Generated by Django 3.2 on 2021-05-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uth_groups_app', '0021_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='folder_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
