# Generated by Django 3.2 on 2021-07-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uth_groups_app', '0023_student_calendar_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iCalUID', models.CharField(max_length=200, null=True)),
                ('participants', models.ManyToManyField(to='uth_groups_app.Student')),
            ],
        ),
    ]
