# Generated by Django 3.2 on 2021-07-07 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uth_groups_app', '0024_googleevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleevent',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='uth_groups_app.course'),
        ),
        migrations.AddField(
            model_name='googleevent',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='uth_groups_app.group'),
        ),
    ]
