# Generated by Django 3.2 on 2021-08-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uth_groups_app', '0029_auto_20210810_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='chat_messages',
            field=models.ManyToManyField(related_name='ChatMessages', to='uth_groups_app.Message'),
        ),
    ]
