# Generated by Django 3.2 on 2021-08-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uth_groups_app', '0030_course_chat_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='chat_messages',
            field=models.ManyToManyField(related_name='ChatMessagesGroup', to='uth_groups_app.Message'),
        ),
    ]
