# Generated by Django 3.2 on 2021-08-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uth_groups_app', '0032_auto_20210810_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='sended_at',
        ),
    ]
