# Generated by Django 3.2 on 2021-08-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uth_groups_app', '0033_rename_created_at_message_sended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_status',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_academic_autorized',
            field=models.BooleanField(default=False),
        ),
    ]
