# Generated by Django 3.2 on 2021-08-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uth_groups_app', '0035_rename_is_academic_autorized_student_is_academic_authorized'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='authorization_code',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
