# Generated by Django 3.2 on 2021-08-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uth_groups_app', '0036_student_authorization_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_email',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
