# Generated by Django 3.2 on 2021-10-20 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uth_groups_app', '0038_auto_20210816_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='join_requests',
            field=models.ManyToManyField(related_name='CourseJoinRequests', to='uth_groups_app.Student'),
        ),
        migrations.AddField(
            model_name='group',
            name='join_requests',
            field=models.ManyToManyField(related_name='GroupJoinRequests', to='uth_groups_app.Student'),
        ),
        migrations.CreateModel(
            name='GroupAdmins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uth_groups_app.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uth_groups_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAdmins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uth_groups_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uth_groups_app.student')),
            ],
        ),
    ]
