# Generated by Django 3.2 on 2021-10-20 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uth_groups_app', '0040_courseadmins_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupadmins',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupadmins',
            name='student',
        ),
        migrations.DeleteModel(
            name='CourseAdmins',
        ),
        migrations.DeleteModel(
            name='GroupAdmins',
        ),
    ]
