# Generated by Django 3.2 on 2021-10-20 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uth_groups_app', '0041_auto_20211020_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAdmins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uth_groups_app.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uth_groups_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAdmins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('more', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uth_groups_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uth_groups_app.student')),
            ],
        ),
    ]
