# Generated by Django 3.2 on 2021-11-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uth_groups_app', '0046_auto_20211020_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='academic_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='academic_status',
        ),
    ]
